# SPDX-License-Identifier: LicenseRef-Boardwright-Source-Available
# Copyright (c) Ryan Hicks

from __future__ import annotations

from dataclasses import dataclass
import json
from pathlib import Path
import re
from typing import Any

from .errors import BoardwrightError
from .sheet_titles import collect_actual_sheet_titles


COMBINED_SHEET_TITLES = Path(".boardwright") / "combined_sheet_titles.env"
COMBINED_NATIVE_DIR = Path("Manufacturing") / "CombinedSources"
MAX_COMBINED_TOC_ENTRIES = 40


COMBINED_NATIVE_YAML = Path("boardwright_resources") / "kibot" / "yaml" / "kibot_out_pdf_combined_native.yaml"
GENERATED_WORKSHEETS = Path(".boardwright") / "generated_worksheets"
COMBINED_SCHEMATIC_WORKSHEET = GENERATED_WORKSHEETS / "combined_schematic.kicad_wks"
MAIN_COMBINED_GROUP_START = "  # Boardwright generated combined native outputs -- start"
MAIN_COMBINED_GROUP_END = "  # Boardwright generated combined native outputs -- end"
MAIN_COMBINED_IMPORT_START = "  # Boardwright generated combined native import -- start"
MAIN_COMBINED_IMPORT_END = "  # Boardwright generated combined native import -- end"


@dataclass(frozen=True)
class NativeCombinedOutputResult:
    manifest: CombinedSheetManifest
    output_names: tuple[str, ...]
    worksheets: tuple[Path, ...]
    yaml_path: Path


@dataclass(frozen=True)
class CombinedPdfInput:
    title: str
    path: Path


@dataclass(frozen=True)
class CombinedPdfPlan:
    enabled: bool
    output_path: Path
    inputs: tuple[CombinedPdfInput, ...]
    toc_enabled: bool = True
    page_numbers_enabled: bool = True
    warnings: tuple[str, ...] = ()


@dataclass(frozen=True)
class CombinedSheet:
    number: int
    section: str
    title: str
    source_kind: str
    source_local_page: int


@dataclass(frozen=True)
class CombinedSheetManifest:
    enabled: bool
    sheets: tuple[CombinedSheet, ...]
    path: Path


def build_combined_pdf_plan(config, root: Path | None = None) -> CombinedPdfPlan:
    project_root = (root or config.root).resolve()
    outputs = getattr(config, "output_settings", {}) or {}
    enabled = _as_bool(outputs.get("combined_review_pdf", False))
    output_path = project_root / "Manufacturing" / "boardwright-combined.pdf"

    return CombinedPdfPlan(
        enabled=enabled,
        output_path=output_path,
        inputs=tuple(_discover_inputs(project_root, output_path)),
        toc_enabled=True,
        page_numbers_enabled=True,
    )


def build_combined_sheet_manifest(config, root: Path | None = None) -> CombinedSheetManifest:
    project_root = (root or config.root).resolve()
    outputs = getattr(config, "output_settings", {}) or {}
    enabled = _as_bool(outputs.get("combined_review_pdf", False))
    sheets = tuple(_combined_sheets(project_root)) if enabled else ()
    return CombinedSheetManifest(enabled=enabled, sheets=sheets, path=project_root / COMBINED_SHEET_TITLES)


def write_combined_sheet_manifest(config, root: Path | None = None) -> CombinedSheetManifest:
    manifest = build_combined_sheet_manifest(config, root)
    if not manifest.enabled:
        if manifest.path.exists():
            manifest.path.unlink()
        return manifest

    manifest.path.parent.mkdir(parents=True, exist_ok=True)
    lines = ["# Generated by Boardwright. Used by KiCad/KiBot text variables for the native combined review PDF."]
    lines.append(f"COMBINED_SHEET_TOTAL={len(manifest.sheets)}")
    for sheet in manifest.sheets[:MAX_COMBINED_TOC_ENTRIES]:
        lines.append(f"SHEET_NAME_{sheet.number}={sheet.title}")
        lines.append(f"SHEET_SECTION_{sheet.number}={sheet.section}")
        lines.append(f"SHEET_SOURCE_KIND_{sheet.number}={sheet.source_kind}")
        lines.append(f"SHEET_SOURCE_PAGE_{sheet.number}={sheet.source_local_page}")
    manifest.path.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")
    return manifest


def write_combined_pdf(config, root: Path | None = None) -> CombinedPdfPlan:
    plan = build_combined_pdf_plan(config, root)
    if not plan.enabled:
        return plan
    if not plan.inputs:
        raise BoardwrightError("Combined PDF is enabled, but no source PDFs were found.")

    try:
        from pypdf import PdfReader, PdfWriter
    except ImportError as exc:
        raise BoardwrightError("Combined PDF output requires the `pypdf` Python package.") from exc

    project_root = (root or config.root).resolve()
    writer = PdfWriter()
    page_index = 0
    bookmark_manifest = _read_combined_sheet_manifest(project_root)
    for item in plan.inputs:
        reader = PdfReader(str(item.path))
        if len(reader.pages) == 0:
            continue
        section_start = page_index
        for page in reader.pages:
            writer.add_page(page)
            page_index += 1
        if not bookmark_manifest:
            parent = writer.add_outline_item(item.title, section_start)
            copied = _copy_source_outline(writer, reader, parent, section_start)
            if not copied:
                titles = _titles_for_input(project_root, item, len(reader.pages))
                for index, _page in enumerate(reader.pages):
                    title = _page_title(item.title, titles, index)
                    writer.add_outline_item(title, section_start + index, parent=parent)

    if page_index == 0:
        raise BoardwrightError("Combined PDF source files did not contain any pages.")
    if bookmark_manifest and page_index >= len(bookmark_manifest):
        for sheet in bookmark_manifest:
            writer.add_outline_item(sheet.title, sheet.number - 1)

    plan.output_path.parent.mkdir(parents=True, exist_ok=True)
    with plan.output_path.open("wb") as handle:
        writer.write(handle)
    return plan


def format_combined_pdf_summary(plan: CombinedPdfPlan) -> str:
    if not plan.enabled:
        return "Combined PDF: disabled."
    if not plan.inputs:
        return f"Combined PDF: enabled, no source PDFs found for {plan.output_path.name}."
    inputs = ", ".join(f"{item.title}={_display_path(item.path, plan.output_path.parent)}" for item in plan.inputs)
    return f"Combined PDF: wrote {_display_path(plan.output_path, plan.output_path.parent)} from {inputs}."


def format_combined_sheet_manifest_summary(manifest: CombinedSheetManifest) -> str:
    if not manifest.enabled:
        return "Combined PDF native contents: disabled."
    return f"Combined PDF native contents: wrote {_display_path(manifest.path, manifest.path.parent)} with {len(manifest.sheets)} sheet title(s)."


def read_combined_sheet_title(root: Path, page_number: int) -> str | None:
    values = _read_env(root / COMBINED_SHEET_TITLES)
    return values.get(f"SHEET_NAME_{page_number}")


def read_combined_sheet_total(root: Path) -> int | None:
    values = _read_env(root / COMBINED_SHEET_TITLES)
    value = values.get("COMBINED_SHEET_TOTAL")
    if value is None:
        return None
    try:
        return int(value)
    except ValueError:
        return None


def native_pcb_sheets(manifest: CombinedSheetManifest) -> tuple[CombinedSheet, ...]:
    return tuple(sheet for sheet in manifest.sheets if sheet.source_kind in {"assembly", "fabrication"})



def prepare_native_combined_outputs(config, root: Path | None = None) -> NativeCombinedOutputResult:
    project_root = (root or config.root).resolve()
    manifest = write_combined_sheet_manifest(config, project_root)
    if not manifest.enabled:
        _clean_native_combined_outputs(project_root)
        return NativeCombinedOutputResult(manifest, (), (), project_root / COMBINED_NATIVE_YAML)

    _prepare_schematic_combined_worksheet(project_root)
    output_names, worksheets = _write_native_pcb_outputs(project_root, manifest)
    _patch_kibot_main_for_native_outputs(project_root, output_names)
    return NativeCombinedOutputResult(
        manifest=manifest,
        output_names=tuple(output_names),
        worksheets=tuple(worksheets),
        yaml_path=project_root / COMBINED_NATIVE_YAML,
    )


def format_native_combined_output_summary(result: NativeCombinedOutputResult) -> str:
    if not result.manifest.enabled:
        return "Combined PDF native PCB pages: disabled."
    return (
        "Combined PDF native PCB pages: "
        f"wrote {len(result.output_names)} output(s), {len(result.worksheets)} worksheet(s)."
    )




def _write_native_pcb_outputs(root: Path, manifest: CombinedSheetManifest) -> tuple[list[str], list[Path]]:
    sheets = native_pcb_sheets(manifest)
    yaml_path = root / COMBINED_NATIVE_YAML
    worksheet_dir = root / GENERATED_WORKSHEETS
    worksheet_dir.mkdir(parents=True, exist_ok=True)
    yaml_path.parent.mkdir(parents=True, exist_ok=True)

    if not sheets:
        yaml_path.write_text("kibot:\n  version: 1\n\noutputs: []\n", encoding="utf-8", newline="\n")
        return [], []

    definitions = _main_definitions(root)
    source_worksheets = _source_worksheet_paths(root, definitions)
    page_blocks = {
        "assembly": _page_blocks(root / "boardwright_resources" / "kibot" / "yaml" / "kibot_out_pdf_assembly.yaml"),
        "fabrication": _page_blocks(root / "boardwright_resources" / "kibot" / "yaml" / "kibot_out_pdf_fabrication.yaml"),
    }
    option_prefixes = {
        "assembly": _option_prefix(root / "boardwright_resources" / "kibot" / "yaml" / "kibot_out_pdf_assembly.yaml"),
        "fabrication": _option_prefix(root / "boardwright_resources" / "kibot" / "yaml" / "kibot_out_pdf_fabrication.yaml"),
    }

    outputs: list[str] = ["kibot:", "  version: 1", "", "outputs:"]
    output_names: list[str] = []
    worksheets: list[Path] = []
    for sheet in sheets:
        blocks = page_blocks.get(sheet.source_kind, ())
        if sheet.source_local_page < 1 or sheet.source_local_page > len(blocks):
            continue
        name = f"pdf_combined_native_{sheet.number:03d}"
        slug = _slug(sheet.title)
        worksheet = worksheet_dir / f"combined_sheet_{sheet.number:03d}.kicad_wks"
        _write_numbered_worksheet(
            source_worksheets[sheet.source_kind],
            worksheet,
            f"SHEET {sheet.number} OF {len(manifest.sheets)}",
            _page_text_variables(root, sheet, definitions),
        )
        worksheets.append(worksheet)
        output_names.append(name)
        prefix = _resolve_placeholders(
            option_prefixes[sheet.source_kind],
            _definition_map_for_kind(sheet.source_kind, definitions),
        )
        prefix = _replace_yaml_option(prefix, "output", f"%f-combined-{sheet.number:03d}-{slug}%I%v.%x")
        prefix = _replace_yaml_option(prefix, "title", f"{sheet.title} DOCUMENT")
        prefix = _replace_yaml_option(
            prefix,
            "sheet_reference_layout",
            "${KIPRJMOD}/" + _posix_path(worksheet.relative_to(root)),
        )
        page_block = _resolve_placeholders(blocks[sheet.source_local_page - 1], _definition_map_for_kind(sheet.source_kind, definitions))
        outputs.extend(
            [
                f"- name: {name}",
                f"  comment: 'Combined review PDF page {sheet.number}: {sheet.title}'",
                "  type: pcb_print",
                "  category: 'Manufacturing/CombinedSources'",
                "  dir: 'Manufacturing/CombinedSources'",
                "  options:",
                _indent(prefix.rstrip(), "    "),
                "    pages:",
                _indent(page_block.strip(), "      "),
                "",
            ]
        )
    yaml_path.write_text("\n".join(outputs).rstrip() + "\n", encoding="utf-8", newline="\n")
    return output_names, worksheets


def _clean_native_combined_outputs(root: Path) -> None:
    _patch_kibot_main_for_native_outputs(root, [])
    yaml_path = root / COMBINED_NATIVE_YAML
    if yaml_path.exists():
        yaml_path.unlink()
    worksheet_dir = root / GENERATED_WORKSHEETS
    if worksheet_dir.is_dir():
        for path in worksheet_dir.glob("combined_sheet_*.kicad_wks"):
            path.unlink()
        schematic_worksheet = root / COMBINED_SCHEMATIC_WORKSHEET
        if schematic_worksheet.exists():
            schematic_worksheet.unlink()


def _prepare_schematic_combined_worksheet(root: Path) -> Path | None:
    source = _schematic_worksheet_path(root)
    if source is None or not source.is_file():
        return None
    target = root / COMBINED_SCHEMATIC_WORKSHEET
    target.parent.mkdir(parents=True, exist_ok=True)
    text = source.read_text(encoding="utf-8")
    text = text.replace("SHEET ${#} OF ${##}", "SHEET ${#} OF ${COMBINED_SHEET_TOTAL}")
    text = text.replace("${#} OF ${##}", "${#} OF ${COMBINED_SHEET_TOTAL}")
    target.write_text(text, encoding="utf-8", newline="\n")
    _patch_schematic_project_worksheet(root, target)
    return target


def _schematic_worksheet_path(root: Path) -> Path | None:
    for path in sorted(root.glob("*.kicad_pro")):
        try:
            data = json.loads(path.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError):
            continue
        if not isinstance(data, dict):
            continue
        schematic = data.get("schematic")
        if not isinstance(schematic, dict):
            continue
        value = str(schematic.get("page_layout_descr_file") or "").strip()
        if value:
            return _resolve_project_path(root, _normalize_project_worksheet(value))
    definitions = _main_definitions(root)
    return _resolve_project_path(
        root,
        definitions.get("SHEET_WKS", "${KIPRJMOD}/Templates/Boardwright_Template_PCB_GIT_A4.kicad_wks"),
    )


def _normalize_project_worksheet(value: str) -> str:
    normalized = value.replace("\\", "/").strip()
    embed_prefix = "kicad-embed://"
    if normalized.startswith(embed_prefix):
        return (Path("Templates") / normalized.removeprefix(embed_prefix).lstrip("/")).as_posix()
    if normalized.startswith("${KIPRJMOD}/"):
        return normalized.removeprefix("${KIPRJMOD}/")
    return normalized


def _patch_schematic_project_worksheet(root: Path, worksheet: Path) -> None:
    worksheet_ref = "${KIPRJMOD}/" + _posix_path(worksheet.relative_to(root))
    for path in sorted(root.glob("*.kicad_pro")):
        try:
            data = json.loads(path.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError):
            continue
        if not isinstance(data, dict):
            continue
        schematic = data.setdefault("schematic", {})
        if not isinstance(schematic, dict):
            continue
        schematic["page_layout_descr_file"] = worksheet_ref
        try:
            path.write_text(json.dumps(data, indent=2) + "\n", encoding="utf-8", newline="\n")
        except PermissionError as exc:
            raise BoardwrightError(
                f"Cannot update schematic worksheet in {path.name}; normalize project file ownership before combined PDF prep."
            ) from exc
        return


def _patch_kibot_main_for_native_outputs(root: Path, output_names: list[str]) -> None:
    path = root / "boardwright_resources" / "kibot" / "yaml" / "kibot_main.yaml"
    if not path.is_file():
        return
    text = path.read_text(encoding="utf-8")
    text = _remove_marked_block(text, MAIN_COMBINED_GROUP_START, MAIN_COMBINED_GROUP_END)
    text = _remove_marked_block(text, MAIN_COMBINED_IMPORT_START, MAIN_COMBINED_IMPORT_END)
    if not output_names:
        text = _remove_group_member(text, "all_group", "combined_native")
        text = _remove_group_member(text, "all_group_k9", "combined_native")
    if output_names:
        group = [MAIN_COMBINED_GROUP_START, "  - name: combined_native", "    outputs:"]
        group.extend(f"      - {name}" for name in output_names)
        group.append(MAIN_COMBINED_GROUP_END)
        text = text.replace("\nimport:\n", "\n" + "\n".join(group) + "\n\nimport:\n", 1)
        text = _add_group_member(text, "all_group", "combined_native")
        text = _add_group_member(text, "all_group_k9", "combined_native")
        imp = "\n".join([
            MAIN_COMBINED_IMPORT_START,
            "  - file: kibot_out_pdf_combined_native.yaml",
            MAIN_COMBINED_IMPORT_END,
        ])
        text = text.replace("\n  # Compress fabrication files", "\n" + imp + "\n\n  # Compress fabrication files", 1)
    path.write_text(text, encoding="utf-8", newline="\n")


def _remove_group_member(text: str, group_name: str, member: str) -> str:
    marker = f"  - name: {group_name}\n    outputs:\n"
    start = text.find(marker)
    if start == -1:
        return text
    insert_at = text.find("\n  - name:", start + len(marker))
    if insert_at == -1:
        insert_at = text.find("\nimport:", start)
    if insert_at == -1:
        insert_at = len(text)
    block = text[start:insert_at]
    line_pattern = re.compile(rf"^\s*- {re.escape(member)}\n?", re.MULTILINE)
    return text[:start] + line_pattern.sub("", block) + text[insert_at:]


def _add_group_member(text: str, group_name: str, member: str) -> str:
    marker = f"  - name: {group_name}\n    outputs:\n"
    start = text.find(marker)
    if start == -1:
        return text
    insert_at = text.find("\n  - name:", start + len(marker))
    if insert_at == -1:
        insert_at = text.find("\nimport:", start)
    block = text[start:insert_at]
    line = f"      - {member}"
    if line in block:
        return text
    return text[:insert_at] + "\n" + line + text[insert_at:]


def _remove_marked_block(text: str, start_marker: str, end_marker: str) -> str:
    pattern = re.compile(rf"\n?{re.escape(start_marker)}.*?{re.escape(end_marker)}\n?", re.DOTALL)
    return pattern.sub("\n", text)


def _source_worksheet_paths(root: Path, definitions: dict[str, str]) -> dict[str, Path]:
    raw = definitions.get("SHEET_WKS", "${KIPRJMOD}/Templates/Boardwright_Template_PCB_GIT_A4.kicad_wks")
    path = _resolve_project_path(root, raw)
    return {"assembly": path, "fabrication": path}


def _resolve_project_path(root: Path, value: str) -> Path:
    value = value.strip().strip("'").strip('"').replace("${KIPRJMOD}", str(root).replace("\\", "/"))
    path = Path(value)
    return path if path.is_absolute() else root / path


def _write_numbered_worksheet(
    source: Path,
    target: Path,
    number_text: str,
    text_variables: dict[str, str] | None = None,
) -> None:
    text = source.read_text(encoding="utf-8")
    text = text.replace("SHEET ${#} OF ${##}", number_text)
    text = text.replace("${#} OF ${##}", number_text.removeprefix("SHEET "))
    text = text.replace("SHEET ${#} OF ${COMBINED_SHEET_TOTAL}", number_text)
    text = text.replace("${#} OF ${COMBINED_SHEET_TOTAL}", number_text.removeprefix("SHEET "))
    for key, value in (text_variables or {}).items():
        text = text.replace("${" + key + "}", value)
    target.write_text(text, encoding="utf-8", newline="\n")


def _page_text_variables(root: Path, sheet: CombinedSheet, definitions: dict[str, str]) -> dict[str, str]:
    values = dict(_document_text_variables(root, sheet.source_kind, definitions))
    if sheet.title:
        values["DRAWING_TITLE"] = sheet.title.upper()
    return values


def _main_definitions(root: Path) -> dict[str, str]:
    path = root / "boardwright_resources" / "kibot" / "yaml" / "kibot_main.yaml"
    text = path.read_text(encoding="utf-8")
    marker = "\ndefinitions:\n"
    index = text.rfind(marker)
    values: dict[str, str] = {}
    if index == -1:
        return values
    for raw in text[index + len(marker):].splitlines():
        match = re.match(r"\s{2}([A-Z0-9_]+):\s*(.*)$", raw)
        if match:
            values[match.group(1)] = match.group(2).strip().strip("'")
    return values


def _document_text_variables(root: Path, kind: str, definitions: dict[str, str]) -> dict[str, str]:
    generated = {
        "assembly": root / "boardwright_resources" / "kibot" / "yaml" / "kibot_document_assembly.generated.yaml",
        "fabrication": root / "boardwright_resources" / "kibot" / "yaml" / "kibot_document_fabrication.generated.yaml",
    }.get(kind)
    values = _definitions_from_yaml(generated) if generated is not None and generated.is_file() else {}
    if values:
        return values
    if kind == "assembly":
        return {
            "DOCUMENT_TYPE": "ASSEMBLY",
            "DRAWING_TITLE": "ASSEMBLY DRAWING",
            "DRAWING_NUMBER": definitions.get("PCBA_NAME", definitions.get("DRAWING_NUMBER", "")),
        }
    return {
        "DOCUMENT_TYPE": "FABRICATION",
        "DRAWING_TITLE": "FABRICATION DRAWING",
        "DRAWING_NUMBER": definitions.get("PCB_NAME", definitions.get("DRAWING_NUMBER", "")),
    }


def _definitions_from_yaml(path: Path) -> dict[str, str]:
    text = path.read_text(encoding="utf-8")
    marker = "\ndefinitions:\n"
    index = text.rfind(marker)
    if index == -1:
        return {}
    values: dict[str, str] = {}
    for raw in text[index + len(marker):].splitlines():
        match = re.match(r"\s{2}([A-Z0-9_]+):\s*(.*)$", raw)
        if match:
            values[match.group(1)] = match.group(2).strip().strip("'")
    return values


def _definition_map_for_kind(kind: str, definitions: dict[str, str]) -> dict[str, str]:
    common = {
        "COLOR_THEME": definitions.get("COLOR_THEME", "KiCad_Theme"),
        "SHEET_WKS": definitions.get("SHEET_WKS", "${KIPRJMOD}/Templates/Boardwright_Template_PCB_GIT_A4.kicad_wks"),
    }
    if kind == "assembly":
        common.update({
            "SCALING": definitions.get("ASSEMBLY_SCALING", "1.0"),
            "FAB_EXCLUDE_FILTER": definitions.get("FILT_TP_EXCLUDE", "exclude_testpoints"),
            "LAYER_TITLE_PAGE": definitions.get("LAYER_TITLE_PAGE", "TitlePage"),
            "LAYER_ASSEMBLY_TEXT_TOP": definitions.get("LAYER_ASSEMBLY_TEXT_TOP", "F.AssemblyText"),
            "LAYER_ASSEMBLY_TEXT_BOTTOM": definitions.get("LAYER_ASSEMBLY_TEXT_BOTTOM", "B.AssemblyText"),
            "LAYER_DNP_CROSS_TOP": definitions.get("LAYER_DNP_CROSS_TOP", "F.DNP"),
            "LAYER_DNP_CROSS_BOTTOM": definitions.get("LAYER_DNP_CROSS_BOTTOM", "B.DNP"),
        })
    else:
        common.update({
            "SCALING": definitions.get("FAB_SCALING", "1.0"),
            "FAB_EXCLUDE_FILTER": definitions.get("FILT_TP_ONLY", "only_testpoints"),
            "LAYER_DRILL_MAP": definitions.get("LAYER_DRILL_MAP", "DrillMap"),
            "LAYER_TP_LIST_TOP": definitions.get("LAYER_TP_LIST_TOP", "F.TestPointList"),
            "LAYER_TP_LIST_BOTTOM": definitions.get("LAYER_TP_LIST_BOTTOM", "B.TestPointList"),
            "PTH_NPTH": definitions.get("GROUP_PTH_NPTH", "yes"),
            "GROUP_ROUND_SLOTS": definitions.get("GROUP_ROUND_SLOTS", "true"),
            "NAME_TP_TOP": definitions.get("CSV_TP_TOP_OUTPUT", "csv_testpoints_top"),
            "NAME_TP_BOTTOM": definitions.get("CSV_TP_BOTTOM_OUTPUT", "csv_testpoints_bottom"),
            "NAME_DRILL_TABLE": definitions.get("CSV_DRILL_TABLE_OUTPUT", "csv_drill_table"),
        })
    return common


def _resolve_placeholders(text: str, definitions: dict[str, str]) -> str:
    for key, value in definitions.items():
        text = text.replace(f"@{key}@", value)
    return text


def _option_prefix(path: Path) -> str:
    text = path.read_text(encoding="utf-8")
    start = text.find("  options:\n")
    pages = text.find("    pages:\n", start)
    if start == -1 or pages == -1:
        return ""
    return _dedent_yaml_block(text[start + len("  options:\n"):pages])


def _page_blocks(path: Path) -> tuple[str, ...]:
    text = path.read_text(encoding="utf-8")
    pages = text.find("    pages:\n")
    if pages == -1:
        return ()
    body_start = text.find("\n      - ", pages)
    end = text.find("\n...", body_start)
    if body_start == -1:
        return ()
    if end == -1:
        end = len(text)
    body = text[body_start:end]
    starts = [m.start() for m in re.finditer(r"\n      - ", body)]
    blocks: list[str] = []
    for index, start in enumerate(starts):
        block_end = starts[index + 1] if index + 1 < len(starts) else len(body)
        blocks.append(_dedent_yaml_block(body[start:block_end]))
    return tuple(blocks)


def _dedent_yaml_block(text: str) -> str:
    lines = text.strip("\n").splitlines()
    indents = [len(line) - len(line.lstrip(" ")) for line in lines if line.strip()]
    if not indents:
        return ""
    width = min(indents)
    return "\n".join(line[width:] if len(line) >= width else line for line in lines).rstrip()


def _replace_yaml_option(text: str, key: str, value: str) -> str:
    pattern = re.compile(rf"^(\s*{re.escape(key)}:\s*).*$", re.MULTILINE)
    quoted = "'" + value.replace("'", "''") + "'"
    if pattern.search(text):
        return pattern.sub(rf"\1{quoted}", text, count=1)
    return text.rstrip() + f"\n{key}: {quoted}\n"


def _indent(text: str, prefix: str) -> str:
    return "\n".join(prefix + line if line else line for line in text.splitlines())


def _slug(value: str) -> str:
    slug = re.sub(r"[^A-Za-z0-9]+", "-", value.strip().lower()).strip("-")
    return slug or "page"


def _posix_path(path: Path) -> str:
    return path.as_posix()

def _copy_source_outline(writer: Any, reader: Any, parent: Any, page_offset: int) -> int:
    try:
        outline = reader.outline
    except Exception:
        return 0
    return _copy_outline_items(writer, reader, outline, parent, page_offset)


def _copy_outline_items(writer: Any, reader: Any, outline: Any, parent: Any, page_offset: int) -> int:
    copied = 0
    last_parent = parent
    for entry in outline or []:
        if isinstance(entry, list):
            copied += _copy_outline_items(writer, reader, entry, last_parent, page_offset)
            continue
        try:
            source_page = reader.get_destination_page_number(entry)
        except Exception:
            continue
        if source_page < 0:
            continue
        title = str(getattr(entry, "title", "") or "Sheet")
        try:
            last_parent = writer.add_outline_item(title, page_offset + source_page, parent=parent)
        except Exception:
            continue
        copied += 1
    return copied


def _discover_inputs(root: Path, output_path: Path) -> list[CombinedPdfInput]:
    native = _native_combined_source_pdfs(root)
    if native:
        schematic = _first_pdf("Schematic", root / "Schematic", output_path)
        return ([schematic] if schematic is not None else []) + native
    return [
        item
        for item in (
            _first_pdf("Schematic", root / "Schematic", output_path),
            _first_pdf("Assembly", root / "Manufacturing" / "Assembly", output_path),
            _first_pdf("Fabrication", root / "Manufacturing" / "Fabrication", output_path),
        )
        if item is not None
    ]


def _native_combined_source_pdfs(root: Path) -> list[CombinedPdfInput]:
    directory = root / COMBINED_NATIVE_DIR
    if not directory.is_dir():
        return []
    selected: dict[int, Path] = {}
    unnumbered: list[Path] = []
    for path in sorted(directory.glob("*.pdf")):
        number = _combined_source_number(path.stem)
        if number is None:
            unnumbered.append(path)
            continue
        existing = selected.get(number)
        if existing is None or _numbered_pdf_page(existing):
            selected[number] = path
    inputs = [
        CombinedPdfInput(_title_from_combined_source_name(path.stem), path)
        for _number, path in sorted(selected.items())
    ]
    inputs.extend(CombinedPdfInput(_title_from_combined_source_name(path.stem), path) for path in unnumbered)
    return inputs


def _combined_source_number(stem: str) -> int | None:
    match = re.match(r".*combined-(\d+)-", stem)
    if not match:
        return None
    try:
        return int(match.group(1))
    except ValueError:
        return None


def _title_from_combined_source_name(stem: str) -> str:
    stem = re.sub(r"-\d+$", "", stem)
    match = re.match(r".*combined-(\d+)-(.+)$", stem)
    if not match:
        return stem
    return match.group(2).replace("-", " ").upper()


def _combined_sheets(root: Path) -> list[CombinedSheet]:
    sheets: list[CombinedSheet] = []
    for index, title in enumerate(_schematic_titles(root), start=1):
        sheets.append(CombinedSheet(len(sheets) + 1, "Schematic", title, "schematic", index))
    for section, kind, yaml_name in (
        ("Assembly", "assembly", "kibot_out_pdf_assembly.yaml"),
        ("Fabrication", "fabrication", "kibot_out_pdf_fabrication.yaml"),
    ):
        for local_index, title in enumerate(_titles_from_kibot_pages(root / "boardwright_resources" / "kibot" / "yaml" / yaml_name), start=1):
            sheets.append(CombinedSheet(len(sheets) + 1, section, title, kind, local_index))
    return sheets


def _schematic_titles(root: Path) -> tuple[str, ...]:
    titles = collect_actual_sheet_titles(root, max_titles=MAX_COMBINED_TOC_ENTRIES)
    trimmed = list(titles)
    while trimmed and set(trimmed[-1]) == {"."}:
        trimmed.pop()
    return tuple(trimmed or titles[:1])


def _first_pdf(title: str, directory: Path, output_path: Path) -> CombinedPdfInput | None:
    if not directory.is_dir():
        return None
    candidates = [
        path
        for path in sorted(directory.glob("*.pdf"))
        if path.resolve() != output_path.resolve() and not _numbered_pdf_page(path)
    ]
    if not candidates:
        return None
    preferred = [path for path in candidates if title.lower() in path.stem.lower()]
    selected = preferred[0] if preferred else candidates[0]
    return CombinedPdfInput(title, selected)


def _titles_for_input(root: Path, item: CombinedPdfInput, page_count: int) -> tuple[str, ...]:
    if item.title == "Schematic":
        titles = collect_actual_sheet_titles(root, max_titles=max(page_count, 1))
    elif item.title == "Assembly":
        titles = _titles_from_kibot_pages(root / "boardwright_resources" / "kibot" / "yaml" / "kibot_out_pdf_assembly.yaml")
    elif item.title == "Fabrication":
        titles = _titles_from_kibot_pages(root / "boardwright_resources" / "kibot" / "yaml" / "kibot_out_pdf_fabrication.yaml")
    else:
        titles = (item.title,)
    return tuple(title for title in titles if title)


def _titles_from_kibot_pages(path: Path) -> tuple[str, ...]:
    if not path.is_file():
        return ()
    titles: list[str] = []
    in_pages = False
    page_indent: int | None = None
    for raw_line in path.read_text(encoding="utf-8", errors="replace").splitlines():
        if re.match(r"^\s{4}pages:\s*$", raw_line):
            in_pages = True
            page_indent = None
            continue
        if not in_pages:
            continue
        stripped = raw_line.strip()
        indent = len(raw_line) - len(raw_line.lstrip(" "))
        if page_indent is None and stripped.startswith("- "):
            page_indent = indent
        elif page_indent is not None and indent <= page_indent and stripped and not stripped.startswith("- "):
            break
        match = re.match(r"(?:-\s*)?title:\s*['\"]?(.*?)['\"]?\s*$", stripped)
        if match:
            title = match.group(1).strip()
            if title and "@" not in title and "%" not in title:
                titles.append(title)
    return tuple(titles)


def _page_title(section: str, titles: tuple[str, ...], index: int) -> str:
    if index < len(titles):
        return titles[index]
    return f"{section} {index + 1}"


def _numbered_pdf_page(path: Path) -> bool:
    stem = path.stem
    head, sep, tail = stem.rpartition("-")
    return bool(head and sep and tail.isdigit())


def _read_env(path: Path) -> dict[str, str]:
    if not path.is_file():
        return {}
    values: dict[str, str] = {}
    for raw_line in path.read_text(encoding="utf-8", errors="replace").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#"):
            continue
        key, sep, value = line.partition("=")
        if sep:
            values[key] = value
    return values


def _read_combined_sheet_manifest(root: Path) -> tuple[CombinedSheet, ...]:
    values = _read_env(root / COMBINED_SHEET_TITLES)
    total = read_combined_sheet_total(root)
    if not total:
        return ()
    sheets: list[CombinedSheet] = []
    for number in range(1, total + 1):
        title = values.get(f"SHEET_NAME_{number}")
        if not title:
            return ()
        section = values.get(f"SHEET_SECTION_{number}", "")
        source_kind = values.get(f"SHEET_SOURCE_KIND_{number}", "")
        try:
            source_page = int(values.get(f"SHEET_SOURCE_PAGE_{number}", "1"))
        except ValueError:
            source_page = 1
        sheets.append(CombinedSheet(number, section, title, source_kind, source_page))
    return tuple(sheets)


def _as_bool(value: Any) -> bool:
    if isinstance(value, bool):
        return value
    return str(value).strip().lower() in {"1", "true", "yes", "on"}


def _display_path(path: Path, root: Path) -> str:
    try:
        return str(path.resolve().relative_to(root.resolve()))
    except ValueError:
        return str(path)
